### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by chinuy** [dream-lab/riot-bench#3]
MVN version: 3.0.5

build log
----
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for in.dream_lab.bm.stream_iot:iot-bm-tasks:jar:0.1
[WARNING] 'profiles.profile[release].plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-assembly-plugin @ in.dream_lab.bm.stream_iot:iot-bm:0.1, /home/vagrant/tool/riot-bench/pom.xml, line 71, column 29
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for in.dream_lab.bm.stream_iot:iot-bm:pom:0.1
[WARNING] 'profiles.profile[release].plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-assembly-plugin @ line 71, column 29
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] IoT-BM
[INFO] IoT-BM-TASKS
[INFO] IoT-BM-STORM
[INFO] IoT-BM-DISTRO
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building IoT-BM 0.1
[INFO] ------------------------------------------------------------------------
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building IoT-BM-TASKS 0.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ iot-bm-tasks ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 57 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ iot-bm-tasks ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ iot-bm-tasks ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 57 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ iot-bm-tasks ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.3:testResources (default-testResources) @ iot-bm-tasks ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/vagrant/tool/riot-bench/modules/tasks/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ iot-bm-tasks ---
[INFO] Compiling 7 source files to /home/vagrant/tool/riot-bench/modules/tasks/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.10:test (default-test) @ iot-bm-tasks ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:2.2:jar (default-jar) @ iot-bm-tasks ---
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building IoT-BM-STORM 0.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ iot-bm-storm ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/vagrant/tool/riot-bench/modules/storm/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ iot-bm-storm ---
[INFO] Compiling 3 source files to /home/vagrant/tool/riot-bench/modules/storm/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/vagrant/tool/riot-bench/modules/storm/src/main/java/in/dream_lab/bm/stream_iot/storm/topo/apps/StatsWithVisualizationTopology.java:[133,20] error: cannot find symbol
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] IoT-BM ............................................ SUCCESS [0.001s]
[INFO] IoT-BM-TASKS ...................................... SUCCESS [3.983s]
[INFO] IoT-BM-STORM ...................................... FAILURE [3.495s]
[INFO] IoT-BM-DISTRO ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.665s
[INFO] Finished at: Wed Dec 13 22:11:10 UTC 2017
[INFO] Final Memory: 9M/216M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project iot-bm-storm: Compilation failure
[ERROR] /home/vagrant/tool/riot-bench/modules/storm/src/main/java/in/dream_lab/bm/stream_iot/storm/topo/apps/StatsWithVisualizationTopology.java:[133,20] error: cannot find symbol
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :iot-bm-storm

**Comment by feeliperodrigoo** [comment]
I'm facing the same problem. But i'm using maven 3.5.2
I changed the maven-compiler-plugin to the 3.7.0 version.
And i got the following error line.

ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project iot-bm-storm: Compilation failure
[ERROR] /home/fdesouza/Documents/RIoT/riot-bench/modules/storm/src/main/java/in/dream_lab/bm/stream_iot/storm/topo/apps/StatsWithVisualizationTopology.java:[133,20] error: cannot find symbol
[ERROR]   symbol:   class AzureBlobUploadTaskBolt
[ERROR]   location: class StatsWithVisualizationTopology

I tried to look for the AzureBlobUploadTaskBolt, to understand better about the error, but i got nothing so far.

**Comment by ChaturvediShilpa** [comment]
Hi ,

The issue is fixed. I guess one import statement was missing for that bolt in the StatsWithVisualizationTopology.java topology file. 

Please take the latest version. Let me know if you are facing any other issue.

**Comment by chinuy** [comment]
yes, it's fixed. Thank you.
